name: "Issue ref"

on:
  pull_request:
    types: [opened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: estrada9166/issue-ref@master
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"