name: Ruby

on:
  pull_request:
  push:

jobs:
  rubocop_check:
    runs-on: ubuntu-latest
    steps:
    - name: Getting files from GitHub
      uses: actions/checkout@v1
    - name: installing Gosu dependencies
      run: |
        sudo apt-get install build-essential libsdl2-dev libgl1-mesa-dev libopenal-dev \
                      libsndfile-dev libmpg123-dev libgmp-dev libfontconfig1-dev
        sudo apt-get install ruby-dev
        sudo gem install bundler
        sudo bundle install --jobs 4 --retry 3
    - name: Rubocop Linter
      uses: andrewmcodes/rubocop-linter-action@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}